
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abed
      POSTGRES_DB: ems
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure your Dockerfile is named 'Dockerfile' and in the same directory
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: ems
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: abed
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ems
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
